apiVersion: v1
kind: Service
metadata:
  name: surrogate-factory
  labels:
    app.kubernetes.io/name: surrogate-factory
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: surrogate-factory
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
